---
- name: Install hardware management and monitoring tools - EL7
  ansible.builtin.yum:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - ipset
      - ipset-service
    state: present
    update_cache: false
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - iproute-tc
      - ipset
      - ipset-service
    state: present
    update_cache: false
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Install from pip the jc module
  ansible.builtin.pip:
    executable: pip3
    name:
      - jc
    extra_args: --user
    state: latest

- name: Enable and start cron
  ansible.builtin.systemd:
    name: crond
    state: started
    enabled: true

- name: User HOME/bin path
  ansible.builtin.copy:
    dest: /etc/profile.d/add_user_paths.sh
    content: |
        pathmunge $HOME/bin
        pathmunge $HOME/.local/bin
    mode: 0644
    owner: root
    group: root
    backup: false
    force: true

