---
- name: Bootstrap ansible requirements on host EL7
  ansible.builtin.raw: yum install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv gcc
  tags: packages
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'

- name: Bootstrap ansible requirements on host EL9
  ansible.builtin.raw: dnf config-manager --set-enabled crb; dnf install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv gcc
  tags: packages
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Bootstrap ansible requirements on host FEDORA
  ansible.builtin.raw: dnf install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv gcc
  tags: packages
  when: ansible_facts[ 'distribution' ] == 'Fedora'

- name: Bootstrap ansible requirements on host UBUNTU
  ansible.builtin.raw: apt install -y python3 python3-dev python3-setuptools python3-pip python3-wheel python3-virtualenv gcc
  tags: packages
  when: ansible_facts[ 'distribution' ] == 'Ubuntu'

