---
- hosts: "{{ target | default('all') }}"
  gather_facts: False

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/pkg_kernelml_install_task.yml"

