---
- hosts: "{{ target | default('all') }}"
  gather_facts: False

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/cfg_smartd_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/pkg_gmond_task.yml"

- name: Do chrony setup
  ansible.builtin.import_playbook: cfg_chrony.yml

- name: Do lldp setup
  ansible.builtin.import_playbook: cfg_lldpd.yml

